language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

addons:
  apt:
    packages:
      - mediainfo

matrix:
  include:
    - php: 7.3
      env: DEPENDENCIES='stable'

  allow_failures:
    - env: DEPENDENCIES='dev'

  fast_finish: true

before_install:
  - composer selfupdate

install:
  - phpenv rehash
  - if [ "$DEPENDENCIES" == "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;
  - if [ "$DEPENDENCIES" != "low" ]; then composer update; fi;
  - if [ "$DEPENDENCIES" == "low" ]; then composer update --prefer-lowest --prefer-stable; fi;

script:
  - 'if [ "$DEPENDENCIES" == "dev" ] || [ "$DEPENDENCIES" == "low" ]; then
      ./vendor/bin/phpunit;
    else
      ./vendor/bin/phpunit --testdox --coverage-text;
    fi;'

notifications:
  email: false
